//! Vector generation helper — prints deterministic FIPS 206 KAT bytes to stdout.
//! Run with: cargo test --test gen_fips206_vectors -- --ignored --nocapture 2>/dev/null

use falcon::safe_api::{DomainSeparation, FnDsaKeyPair, FnDsaSignature, PreHashAlgorithm};

fn hex(b: &[u8]) -> String {
    b.iter()
        .map(|x| format!("{:02x}", x))
        .collect::<Vec<_>>()
        .join("")
}

fn print_vector(
    label: &str,
    key_seed: &[u8],
    logn: u32,
    msg: &[u8],
    sign_seed: &[u8],
    domain: &DomainSeparation,
) {
    let kp = FnDsaKeyPair::generate_deterministic(key_seed, logn).unwrap();
    let sig = kp.sign_deterministic(msg, sign_seed, domain).unwrap();
    // Verify it works
    FnDsaSignature::verify(sig.to_bytes(), kp.public_key(), msg, domain).unwrap();

    println!("// {label}");
    println!("//   pk  = {}", hex(kp.public_key()));
    println!("//   sig = {}", hex(sig.to_bytes()));
    println!();
}

#[test]
#[ignore]
fn gen_vectors() {
    println!();
    println!("// =====================================================================");
    println!("// Auto-generated FIPS 206 deterministic KAT vectors");
    println!("// Generated by: cargo test --test gen_fips206_vectors -- --ignored --nocapture");
    println!("// =====================================================================");
    println!();

    let msg = b"FIPS 206 FN-DSA Known Answer Test";

    // FN-DSA-512 vectors
    print_vector(
        "FN-DSA-512 / DomainSeparation::None",
        b"fips206-kat-key-seed-512",
        9,
        msg,
        b"fips206-kat-sign-seed",
        &DomainSeparation::None,
    );

    print_vector(
        "FN-DSA-512 / DomainSeparation::Context(b\"fips206-ctx-v1\")",
        b"fips206-kat-key-seed-512",
        9,
        msg,
        b"fips206-kat-sign-seed",
        &DomainSeparation::Context(b"fips206-ctx-v1"),
    );

    print_vector(
        "FN-DSA-512 / Prehashed SHA-256, no ctx",
        b"fips206-kat-key-seed-512",
        9,
        msg,
        b"fips206-kat-sign-seed",
        &DomainSeparation::Prehashed {
            alg: PreHashAlgorithm::Sha256,
            context: b"",
        },
    );

    print_vector(
        "FN-DSA-512 / Prehashed SHA-512, ctx=b\"fips206-ctx-v1\"",
        b"fips206-kat-key-seed-512",
        9,
        msg,
        b"fips206-kat-sign-seed",
        &DomainSeparation::Prehashed {
            alg: PreHashAlgorithm::Sha512,
            context: b"fips206-ctx-v1",
        },
    );

    // FN-DSA-1024 vectors
    print_vector(
        "FN-DSA-1024 / DomainSeparation::None",
        b"fips206-kat-key-seed-1024",
        10,
        msg,
        b"fips206-kat-sign-seed",
        &DomainSeparation::None,
    );

    print_vector(
        "FN-DSA-1024 / Prehashed SHA-512, ctx=b\"fips206-ctx-v1\"",
        b"fips206-kat-key-seed-1024",
        10,
        msg,
        b"fips206-kat-sign-seed",
        &DomainSeparation::Prehashed {
            alg: PreHashAlgorithm::Sha512,
            context: b"fips206-ctx-v1",
        },
    );
}
